definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        /hst:sitemap:
          jcr:primaryType: hst:sitemap
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
          /base-layout:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/alvanthippoproject/base-layout.ftl
          /base-top-menu:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/alvanthippoproject/base-top-menu.ftl
          /base-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/alvanthippoproject/base-footer.ftl
          /homepage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/alvanthippoproject/homepage-main.ftl
          /pagenotfound-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/alvanthippoproject/pagenotfound-main.ftl
          /eventspage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hstdefault/eventspage-main.ftl
          /newspage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hstdefault/newspage-main.ftl
          /search-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/alvanthippoproject/search-main.ftl
          /contentlist-main-contentlist:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hstdefault/contentlist-main-contentlist.ftl
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
        /hst:sitemapitemhandlers:
          jcr:primaryType: hst:sitemapitemhandlers
        /hst:catalog:
          jcr:primaryType: hst:catalog
          /alvanthippoproject-catalog:
            jcr:primaryType: hst:containeritempackage
      /alvanthippoproject:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /alvanthippoprojectnl:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
