definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        /hst:sitemap:
          jcr:primaryType: hst:sitemap
          /root:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/homepage
            hst:pagetitle: Home Page
            hst:refId: root
          /_any_:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
          /pagenotfound:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:pagetitle: Not Found Page
            hst:refId: pagenotfound
          /events:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/eventslist
            hst:pagetitle: List of Events
            hst:relativecontentpath: events
            /_any_.html:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/eventspage
              hst:relativecontentpath: ${parent}/${1}
            /_any_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/eventslist
              hst:relativecontentpath: ${parent}/${1}
          /news:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/newslist
            hst:pagetitle: List of News Items
            hst:relativecontentpath: news
            /_any_.html:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/newspage
              hst:relativecontentpath: ${parent}/${1}
            /_any_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/newslist
              hst:relativecontentpath: ${parent}/${1}
          /robots.txt:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/robotstxt
            hst:hiddeninchannelmanager: true
            hst:relativecontentpath: ../administration/robots
          /search:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/search
            hst:pagetitle: Search Results
            hst:refId: search
          /content:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/contentlist
            hst:pagetitle: List of Simple Documents
            hst:relativecontentpath: content
            /_any_.html:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/contentpage
              hst:relativecontentpath: ${parent}/${1}
            /_any_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/contentlist
              hst:relativecontentpath: ${parent}/${1}
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
          /base-layout:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/alvanthippoproject/base-layout.ftl
          /base-top-menu:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/alvanthippoproject/base-top-menu.ftl
          /base-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/alvanthippoproject/base-footer.ftl
          /homepage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/alvanthippoproject/homepage-main.ftl
          /pagenotfound-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/alvanthippoproject/pagenotfound-main.ftl
          /eventspage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hstdefault/eventspage-main.ftl
          /newspage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hstdefault/newspage-main.ftl
          /search-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/alvanthippoproject/search-main.ftl
          /contentlist-main-contentlist:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hstdefault/contentlist-main-contentlist.ftl
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
        /hst:sitemapitemhandlers:
          jcr:primaryType: hst:sitemapitemhandlers
        /hst:catalog:
          jcr:primaryType: hst:catalog
          /alvanthippoproject-catalog:
            jcr:primaryType: hst:containeritempackage
      /alvanthippoproject:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /alvanthippoprojectnl:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
